------------------------
-- ripulitura db
------------------------
--
DROP TABLE PERSONA;
--
DROP TABLE TELEFONIA;
--
DROP TABLE AZIENDA;
--
DROP TABLE CLIENTE;
--
DROP TABLE CONTO;
--
DROP TABLE FILIALE;
--
DROP TABLE DIPENDENTE;
--
DROP TABLE PUBBLICITA;
--
DROP TABLE CONTABILE;
--
DROP TABLE ASSICURATORE;
--
DROP TABLE GRUPPO_ASSISTENZA;
--
DROP TABLE BANCHIERE;
--
DROP TABLE SCRITTURE_CONTABILI;
--
DROP TABLE ASSICURAZIONE;
--
DROP TABLE SUPPORTO;
--
DROP TABLE OPERAZIONE;
--
DROP TABLE DEPOSITO;
--
DROP TABLE PRESTITO;
--
DROP TABLE TRANSAZIONE;
-------------------------
-- creazione tabelle db
-------------------------
CREATE TABLE PERSONA(
CF                CHAR(16) NOT NULL,
NOME              VARCHAR2(30) NOT NULL,
COGNOME           VARCHAR2(30) NOT NULL,
VIA               VARCHAR2(20),
CAP               VARCHAR2(5),
CITTA             VARCHAR2(30),
EMAIL             VARCHAR2(45) PRIMARY KEY,
DATA_DI_NASCITA   DATE NOT NULL,
SESSO             CHAR(1));
--
CREATE TABLE TELEFONIA(
TELEFONO          VARCHAR2(15) NOT NULL,
EMAIL_T VARCHAR2(45) PRIMARY KEY,
CONSTRAINT FK_TELEFONO FOREIGN KEY (EMAIL_T) REFERENCES PERSONA(EMAIL)
);
--
CREATE TABLE AZIENDA(
NOME_AZIENDA VARCHAR2(30) PRIMARY KEY,
SERVIZI VARCHAR2(25),
FATTURATO NUMBER,
TELEFONO_AZIENDA VARCHAR2(15));
--
CREATE TABLE CLIENTE(
EMAIL_C    VARCHAR2(45) PRIMARY KEY,
CARTA_DI_CREDITO  VARCHAR2(19) NOT NULL,
REDDITO NUMBER NOT NULL,
NOME_A VARCHAR2(30),
CONSTRAINT FK_CLIENTE FOREIGN KEY (EMAIL_C) REFERENCES PERSONA(EMAIL),
CONSTRAINT FK_AZIENDA FOREIGN KEY (NOME_A) REFERENCES AZIENDA(NOME_AZIENDA));
--
CREATE TABLE CONTO(
COD_CONTO         VARCHAR2(50) PRIMARY KEY,
BILANCIO          NUMBER NOT NULL,
ADDEBITO          NUMBER,
FEMAIL_C1         VARCHAR2(45),
CONSTRAINT FK_CONTO  FOREIGN KEY (FEMAIL_C1) REFERENCES CLIENTE(EMAIL_C));
--
CREATE TABLE FILIALE(
N_SEDI                   NUMBER ,
NOME_FILIALE             VARCHAR2(25) PRIMARY KEY,
EMAIL_FILIALE            VARCHAR2(30));
--
CREATE TABLE DIPENDENTE(
NUMERO_TESSERINO NUMBER,
NOME_F VARCHAR2(25),
EMAIL_D VARCHAR2(45) PRIMARY KEY,
CONSTRAINT FK_D FOREIGN KEY(EMAIL_D) REFERENCES PERSONA(EMAIL),
CONSTRAINT FK_FILIALE FOREIGN KEY(NOME_F) REFERENCES FILIALE(NOME_FILIALE));
--
CREATE TABLE PUBBLICITA(
NOME_PUBBLICITA  VARCHAR2(30),
CANALE_TRASMISSIONE  VARCHAR2(30),
DURATA_PUBBLICITA NUMBER,
NOME_FI VARCHAR2(25),
PRIMARY KEY(NOME_PUBBLICITA,NOME_FI),
CONSTRAINT FK_FI FOREIGN KEY(NOME_FI) REFERENCES FILIALE(NOME_FILIALE));
--
CREATE TABLE CONTABILE(
EMAIL_CON VARCHAR2(45) PRIMARY KEY,
DOCUMENTAZIONE_CONTABILE VARCHAR2(30),
CONSTRAINT FK_DIPE FOREIGN KEY(EMAIL_CON) REFERENCES DIPENDENTE(EMAIL_D));
--
CREATE TABLE ASSICURATORE(
EMAIL_ASS VARCHAR2(45) PRIMARY KEY,
ANALISI_POLIZZA NUMBER,
CONSTRAINT FK_DIPE1 FOREIGN KEY(EMAIL_ASS) REFERENCES DIPENDENTE(EMAIL_D));
--
CREATE TABLE GRUPPO_ASSISTENZA(
EMAIL_ASSI VARCHAR2(45) PRIMARY KEY,
ANALISI_RICHIESTA VARCHAR2(45),
CONSTRAINT FK_DIPE2 FOREIGN KEY(EMAIL_ASSI) REFERENCES DIPENDENTE(EMAIL_D));
--
CREATE TABLE BANCHIERE(
EMAIL_B VARCHAR2(45) PRIMARY KEY,
ASSISTENZA_OPERAZIONI VARCHAR2(71),
CONSTRAINT FK_DIPE3 FOREIGN KEY(EMAIL_B) REFERENCES DIPENDENTE(EMAIL_D));
--
CREATE TABLE SCRITTURE_CONTABILI(
TIPO_S_C VARCHAR2(25),
DATA_SCRITTURA_ULTIMA DATE,
EMAIL_CONTA VARCHAR2(45),
PRIMARY KEY (TIPO_S_C,EMAIL_CONTA),
CONSTRAINT FK_SC FOREIGN KEY(EMAIL_CONTA) REFERENCES CONTABILE(EMAIL_CON));
--
CREATE TABLE ASSICURAZIONE(
NOME_A VARCHAR2(25) PRIMARY KEY,
DATA DATE,
EMAIL_A VARCHAR(45),
EMAIL_CL VARCHAR(45),
CONSTRAINT FK_A FOREIGN KEY(EMAIL_A) REFERENCES ASSICURATORE(EMAIL_ASS),
CONSTRAINT FK_C FOREIGN KEY(EMAIL_CL) REFERENCES CLIENTE(EMAIL_C));
--
CREATE TABLE SUPPORTO(
NUMERO_PROTOCOLLO NUMBER PRIMARY KEY,
TIPO_PROBLEMA VARCHAR2(50),
EMAIL_CLI VARCHAR2(45),
CONSTRAINT FK_CL FOREIGN KEY(EMAIL_CLI) REFERENCES CLIENTE (EMAIL_C));
--
CREATE TABLE OPERAZIONE(
FEMAIL_B          VARCHAR2(45),
FCOD_CONTO        VARCHAR2(50),
ID_OPERAZIONE     VARCHAR2(10) PRIMARY KEY,
CIFRA             NUMBER,
DATA1              DATE,
TIPO_OPERAZIONE   VARCHAR2(30),
CONSTRAINT FK_CONTO1  FOREIGN KEY (FCOD_CONTO) REFERENCES CONTO(COD_CONTO),
CONSTRAINT FK_EMAILBANCHIERI FOREIGN KEY (FEMAIL_B) REFERENCES BANCHIERE(EMAIL_B));
--
CREATE TABLE DEPOSITO(
SERVIZIO_DI_CASSA       VARCHAR2(24),
TIPO_DEPOSITO            VARCHAR2(20),
ID_OPERAZIONE3          VARCHAR2(10) PRIMARY KEY,
CONSTRAINT FK_OPERAZIONE FOREIGN KEY(ID_OPERAZIONE3) REFERENCES OPERAZIONE(ID_OPERAZIONE));
--
CREATE TABLE PRESTITO(
PROVA_GARANZIA    CHAR(16),
DURATA_PRESTITO   NUMBER,
ID_OPERAZIONE1    VARCHAR2(10) PRIMARY KEY,
CONSTRAINT FK_OPERAZIONE1 FOREIGN KEY(ID_OPERAZIONE1) REFERENCES OPERAZIONE(ID_OPERAZIONE));
--
CREATE TABLE TRANSAZIONE(
MODALITA_PAGAMENTO      VARCHAR2(20),
MODALITA_TRANSAZIONE    VARCHAR2(30),
POLIZZA                  VARCHAR2(25),
ID_OPERAZIONE2          VARCHAR2(10) PRIMARY KEY,
CONSTRAINT FK_OPERAZIONE2 FOREIGN KEY(ID_OPERAZIONE2) REFERENCES OPERAZIONE(ID_OPERAZIONE));



 

       




