--CLIENTE: PW: CLIENTE

GRANT CREATE SESSION TO CLIENTE;
GRANT SELECT,UPDATE ON PERSONA TO CLIENTE;
GRANT SELECT,UPDATE ON CLIENTE TO CLIENTE;
GRANT SELECT,UPDATE ON OPERAZIONE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE_CREA_TRANSAZIONE TO CLIENTE;

--CONTABILE: PW: CONTABILE

GRANT CREATE SESSION TO CONTABILE;
GRANT SELECT,UPDATE ON DIPENDENTE TO CONTABILE;
GRANT SELECT,UPDATE ON CONTABILE TO CONTABILE;
GRANT ALL ON SCRITTURE_CONTABILI TO CONTABILE;

--ASSICURATORE: PW: ASSICURATORE

GRANT CREATE SESSION TO ASSICURATORE;
GRANT SELECT,UPDATE ON DIPENDENTE TO ASSICURATORE;
GRANT SELECT,UPDATE ON ASSICURATORE TO ASSICURATORE;
GRANT ALL ON ASSICURAZIONE TO ASSICURATORE;

--GRUPPO_ASSISTENZA: PW:ASSISTENZA

GRANT CREATE SESSION TO ASSISTENZA;
GRANT SELECT,UPDATE ON DIPENDENTE TO GRUPPO_ASSISTENZA;
GRANT SELECT,UPDATE ON GRUPPO_ASSISTENZA TO GRUPPO_ASSISTENZA
GRANT ALL ON SUPPORTO TO GRUPPO_ASSISTENZA;

--BANCHIERE PW:BANCHIERE

GRANT CREATE SESSION TO BANCHIERE;
GRANT SELECT,UPDATE ON DIPENDENTE TO BANCHIERE;
GRANT SELECT,UPDATE ON BANCHIERE TO BANCHIERE;
GRANT ALL ON OPERAZIONE TO BANCHIERE;
GRANT ALL ON CONTO TO BANCHIERE;
GRANT EXECUTE ON PROCEDURE_ELIMINA_UN_PRESTITO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE_AGGIORNARE_DEPOSITO TO CLIENTE;

--DIPENDENTE PW:DIPENDENTE

GRANT EXECUTE ON PROCEDURE_AGGIORNARE_PUBBLICITA TO DIPENDENTE;


